### ISSUE TITLE
Feature request: when right click, actually show an example of the conversion

### ISSUE THREAD

**Issue by jayli3n** [marclipovsky/vscode-string-manipulation#38] opened 2022-11-04 07:39 UTC
When you select all the strings you want to convert, and right click, it would be great to also show an example of what the conversion does. Often times, we dont know the name of the casing, or its just easier to see the final form quickly.

Current:
![image](https://user-images.githubusercontent.com/44139980/199918126-8151219c-bccb-4236-95e3-13d2aba57ad9.png)

New feature:
![image](https://user-images.githubusercontent.com/44139980/199918593-1de78aea-ae86-4ac9-a45d-fa0fc78039cd.png)

**Comment by marclipovsky** [comment] 2023-01-28 03:41
This should be possible however I do not want to clutter up the menu UI. I'll consider if more folks +1 this request.

**Comment by marclipovsky** [comment] 2024-09-28 02:43
Checkout my suggestion in #49 about annotating text as you hover over options. Similar to how you can preview a color scheme as you go through color scheme options before actually selecting.

**Comment by marclipovsky** [comment] 2024-09-28 02:45
Duplicate of #49

**Closed** 2024-09-28 02:45 UTC
